### ISSUE TITLE
FRONT END - Caching Issues

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#85] opened 2015-09-20 04:48 UTC
Are you guys working our website right now. 
The site is seriously keep having problem with caching
Products are all in stock , the next thing its all out of stock

We haven't uploaded anything !!

**Comment by supremesupports** [comment] 2015-09-20 05:02
hi,
Please provide some screenshot. The problem is not clear to us.
Thanks

**Comment by Stellyclothing** [comment] 2015-09-22 05:34
Hey @supremesupports @wildfirecreative 
![screen shot 2015-09-22 at 2 51 46 pm](https://cloud.githubusercontent.com/assets/9522928/10011544/4389bcee-613f-11e5-9d35-38b33c95f618.png)

http://stelly.com.au/3-accessories

**Comment by wildfirecreative** [comment] 2015-09-22 05:47
I just looked at this now and it shows up fine

<img width="1257" alt="screen shot 2015-09-22 at 3 39 03 pm" src="https://cloud.githubusercontent.com/assets/9874220/10011625/8888a7b4-6140-11e5-8d69-295998ad9e3b.png">

**Comment by wildfirecreative** [comment] 2015-09-29 23:42
Please close this issue if it is no longer current

**Closed** 2015-10-01 02:59 UTC
Labels: bug
