### ISSUE TITLE
BACKEND - Prestashop Contanstaly Logging me out of the CMS 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#65] opened 2015-09-09 12:51 UTC
hi @supremesupports 
I have to constantly log in all the time 
Can you have a look also

Thanks
Josh

**Comment by supremesupports** [comment] 2015-09-11 03:09
please use the "Keep me logged in" option in the login box

![login](https://cloud.githubusercontent.com/assets/12905649/9806296/cd476744-5864-11e5-94fe-abcac537d156.png)

**Comment by wildfirecreative** [comment] 2015-09-29 23:37
This is not a bug, and a solution has been provided - please close this now.

**Closed** 2015-10-13 04:28 UTC
Labels: bug, Developer actioned
